security:
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: shop
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            logout:
                path:   /logout
                target: /
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: "/.*", role: IS_AUTHENTICATED_ANONYMOUSLY }
